export const Styles = {
  footerContainer: {
    position: "absolute",
    bottom: 0,
    height: "25%",
    width: "100%",
    background: "#A4755D",
  },
  footerBottomRightSvg: {
    position: "absolute",
    right: 0,
    bottom: 0,
  },
  footerTopLeftSvg: {
    position: "absolute",
  },
  footerTopRightSvg: {
    position: "absolute",
    right: 0,
  },
  socialMediaContainer: {
    display: "flex",
    justifyContent: "space-between",
    flexDirection: "row",
    paddingTop: "1rem",
  },
  menuTextContainer: {
    display: "flex",
    flexDirection: "column",
    width: "fit-content",
    height: "100%",
    marginLeft: "1rem",
    textAlign: "center",
  },
  menuText: {
    color: "#F9FDFE",
    fontWeight: 600,
    fontSize: "36px",
    lineHeight: "40px",
  },
  socialMediaIconsContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    marginRight: "2rem",
    paddingTop: "0.5rem",
    width: "fit-content",
  },
  socialMediaIcon: {
    width: "24px",
    height: "24px",
  },
  contactInfo: {
    display: "flex",
    flexDirection: "column",
    textAlign: "center",
    color: "#FFFFFF",
    mt: 1,
  },
  policyButton: {
    background: "#F9FDFE",
    color: "#A4755D",
    fontWeight: "500",
    lineHeight: "16px",
    borderRadius: "32px",
    textTransform: "none",
  },
  footerText: {
    display: "flex",
    color: "#FFFFFF",
    justifyContent: "center",
    alignContent: "center",
    fontSize: "12px",
    paddingTop: "1rem",
  },
  footerLink: {
    textDecoration: "none",
    color: "#FFFFFF",
  },
};